---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/resources/yaml-lint.yml
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
      host_key_checking: false
  inventory:
    host_vars:
      instance:
        provider_server: ${F5_SERVER:-localhost}
        provider_user: ${F5_USER:-admin}
        provider_password: ${F5_PASSWORD:-secret}
  env:
    ANSIBLE_ROLES_PATH: ../../../
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: integration
verifier:
  name: testinfra
  lint:
    name: flake8
